image:
- Visual Studio 2017

configuration:
  - Release

platform:
  - Win32
  - x64

before_build:
  - cmd: git -C .. clone -q https://github.com/MediaArea/zlib.git
  - ps: >-
      $Env:PATH += ";" + (Get-ChildItem "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\*\bin\HostX64\x86")[0].FullName;
      $Env:PATH += ";" + (Get-ChildItem "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\*\bin\HostX64\x64")[0].FullName;
      If ($Env:PLATFORM -Eq "Win32") {
        Push-Location ..\zlib\contrib\masmx86
        ml /nologo /coff /safeseh /Zi /c /Flmatch686.lst match686.asm
        ml /nologo /coff /safeseh /Zi /c /Flinffas32.lst inffas32.asm
        Pop-Location
      } Else {
        Push-Location ..\zlib\contrib\masmx64
        ml64 /nologo /Zi /c /Flinffasx64 inffasx64.asm
        ml64 /nologo /Zi /c /Flgvmat64 gvmat64.asm
        Pop-Location
      }

build_script:
  - cmd: >|
    set VSCMD_START_DIR=%CD%
    call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"
     if %PLATFORM% == "Win32" (
       MSbuid /verbosity:quiet /p:Configuration=Release;Platform=Win32 Project\MSVC2017\ZenLib_MSVC.sln
       MSbuid /verbosity:quiet /p:Configuration=Release;Platform=Win32 Project\MSVC2017\ZenLib_UWP.sln
     ) else (
       MSbuid /verbosity:quiet /p:Configuration=Release;Platform=x64 Project\MSVC2017\ZenLib_MSVC.sln
       MSbuid /verbosity:quiet /p:Configuration=Release;Platform=x64 Project\MSVC2017\ZenLib_UWP.sln
     )
